### PR TITLE
Melody and Tennet

### PR DESCRIPTION
**Pull request by NynjaOrca**

### CODE REVIEW

**Comment by NeonDodongo** [comment]
Yeah that's cool, where'd those names come from?

**Comment by NynjaOrca** [comment]
I just made them. I didn't think to hard. I know that Melody is a good name for a female hero because when I hear Melody I think of a total babe. And Tennet was because I think male Heros that stick have a certain sound to them rather than the actual characters itself. And I thought Tennet sounded cool. So it was chosen.

**Comment by NeonDodongo** [comment]
Lol oh i gotcha. I kind of want the player to be able to name themself, though we could do what Pokemon does and have default names or create a new name and yeah i'm all down for that

**Comment by NynjaOrca** [comment]
Yeah they're placeholder names for the hero. You can choose your own  and NPC will call you by what you put in but this is the default name.

**Pull request merged**
