### PR TITLE
Update Pallenova_GDD.md

### PR DESCRIPTION
**Pull request by NynjaOrca**
Ln 185

### CODE REVIEW

**Comment by NynjaOrca** [comment]
How bout now?

**Comment by NynjaOrca** [comment]
This is an alternative form of communication

**Comment by NynjaOrca** [comment]
WHOA DEUD!

**Comment by NynjaOrca** [comment]
I also have a message that says "Pull request successfully merged and closed"

**Comment by NeonDodongo** [comment]
Right on, this site rules.

**Pull request merged**
